services:
    mosquitto:
        image: eclipse-mosquitto:2
        restart: unless-stopped
        ports:
            - 1883:1883
        environment:
            - TZ=Asia/Bangkok
        volumes:
            - ./docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
            - ./docker/mosquitto/data:/mosquitto/data
        logging:
            driver: 'json-file'
            options:
                max-size: '20m'
                max-file: '10'

    mosquitto_logger:
        image: eclipse-mosquitto:2
        restart: unless-stopped
        depends_on:
            - mosquitto
        environment:
            - TZ=Asia/Bangkok
        volumes:
            - ./docker/mosquitto/log:/mnt/log
        entrypoint: >
            sh -c "mosquitto_sub -h mosquitto -t '#' -v | while read line; do 
                     echo \"$$(date -Iseconds) | $$line\" >> /mnt/log/payload.log; 
                   done"

    postgres:
        image: postgis/postgis:16-3.5
        restart: unless-stopped
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        ports:
            - 127.0.0.1:${POSTGRES_PORT}:5432
        environment:
            - TZ=Asia/Bangkok
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=qgis

    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - 127.0.0.1:${REDIS_PORT}:6379

    mediamtx:
        image: bluenviron/mediamtx:1
        ports:
            - '8554:8554' # RTSP
            - '1935:1935' # RTMP
            - '8888:8888' # HLS
            - '8889:8889' # WebRTC
            - '9997:9997' # Control API
            - '10000:10000/udp' # WebRTC Data
        environment:
            - MTX_WEBRTCADDITIONALHOSTS=${PUBLIC_IP}
        volumes:
            - ./docker/mediamtx/config/mediamtx.yml:/mediamtx.yml
        restart: unless-stopped
